### ISSUE TITLE
Getting error when using lightnessCorrection with scale

### ISSUE THREAD

**Issue by afternoon2** [gka/chroma.js#183]
First of all, @gka, big thank you for your work on this awesome library! 

I'm setting up a javascript module that generates gradients using chroma.js and this is what I am getting in the console when I try to use scale with some mode and lightness correction:

```
Uncaught TypeError: u(...).lab is not a function
    at x (VM102 chroma.min.js:formatted:1850)
    at u (VM102 chroma.min.js:formatted:1750)
    at r (VM102 chroma.min.js:formatted:1790)
```

The console also gives me a view where the problem occurs in my library. It's while the scale output creation:

```javascript
{
            key: '_createBase',
            value: function _createBase(scale) {
                var base = [];
                for (var i = 0; i < this.options.samples; i++) {
                    base.push(scale(i / this.options.samples)); // here
                }
                return base;
            }
```

Link to the test pen [here](https://codepen.io/jakub_antolak/pen/5e1c9fb9561eb71e8c0d7a02e1df5e97)

(change lightnessCorrection and color modes)

I also noticed that when I do the same in my other pen that uses the same technique, there is no problem at all. Or rather it is a bug in my newest code 🐞 

Link to the working example [here](https://codepen.io/jakub_antolak/pen/PeaZKE)

**Comment by afternoon2** [comment]
And here's the output from the jest test suite:

```javascript
TypeError: getColor(...).lab is not a function

      65 |         const base = []
      66 |         for (let i = 0; i < this.options.samples; i++) {
    > 67 |             base.push(scale(i / this.options.samples))
         |                       ^
      68 |         }
      69 |         return base
      70 |     }

      at tmap (node_modules/chroma-js/chroma.js:2285:34)
      at getColor (node_modules/chroma-js/chroma.js:2163:13)
      at f (node_modules/chroma-js/chroma.js:2206:18)
      at Base._createBase (src/base/Base.js:67:23)
      at Base.get (src/base/Base.js:39:27)
      at Object.<anonymous> (tests/base.test.js:31:33)
```

**Comment by afternoon2** [comment]
Ok, it seems that I 'fixed' this by changing the type of the input colors from the rgba number array to css rgba string. 😅 Sorry for the rush, I'm closing the issue.
